name: Deploy to s3

on:
  push:
    branches:
      - main
env:
  SOURCE_DIST: './dist'
  AWS_S3_BUCKET_STATIC: 'pos-upload-widget-web-static'
  AWS_S3_BUCKET_CDN: 'pos-upload-widget-web-cdn'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dependencies
        run: |
          npm install

      - name: Build app
        id: build-app
        run: |
          npm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        id: sync-to-s3
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_STATIC }} --delete --exclude '.*git*'

      - name: Sync to S3 cdn
        id: sync-to-s3-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_CDN }} --delete --exclude '.*git*'
